[package]
name = "meridian-renderer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
meridian-core = { path = "../meridian_core" }
meridian-diagnostics = { path = "../meridian_diagnostics" }
meridian-platform = { path = "../meridian_platform" }
meridian-rhi = { path = "../meridian_rhi" }

[lints]
workspace = true
