[workspace]
resolver = "2"
members = [
    "engine/*",
    "editor/*",
]
exclude = ["game/*"]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bybrooklyn/meridian"

[workspace.dependencies]
bevy_ecs = { version = "0.19.0", default-features = false, features = ["std", "multi_threaded"] }
blake3 = "1.8.5"
naga = { version = "30.0.0", default-features = false, features = ["wgsl-in"] }
png = "0.18.1"
pollster = "0.4.0"
rapier3d = { version = "0.34.0", default-features = false, features = ["dim3", "f32", "std", "enhanced-determinism"] }
wgpu = "30.0.0"
winit = "0.30.13"
jsonschema = { version = "0.33.0", default-features = false }
pulldown-cmark = { version = "0.13.0", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
walkdir = "2.5.0"
cosmic-text = { version = "0.19.0", default-features = false, features = ["std", "swash"] }
unicode-segmentation = "1.13.3"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
