[package]
name = "meridian-ui-editor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
meridian-core = { path = "../../engine/meridian_core" }
meridian-editor-core = { path = "../meridian_editor_core" }
meridian-ui = { path = "../../engine/meridian_ui" }

[lints]
workspace = true
