#!/usr/bin/env python3
"""Generate the Meridian UI 1.0 SVG review corpus from one source manifest.

Generator: scripts/generate_ui_mockups.py
Input: docs/production/ui-mockups/mockups.json
Schema: meridian.ui-mockup-set/v1
Version: 1.0.0
Regenerate: python3 scripts/generate_ui_mockups.py
"""

from __future__ import annotations

import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "docs/production/ui-mockups/mockups.json"
OUT = MANIFEST.parent

COLOR = {
    "background": "#090b0b",
    "surface": "#121515",
    "border": "#292d2c",
    "primary": "#e3e1d8",
    "secondary": "#929790",
    "muted": "#686e68",
    "destructive": "#a73732",
    "destructive_hover": "#c04b44",
    "positive": "#8d8961",
    "warning": "#c0964e",
}

WORKSPACES = ["World", "Modeler", "UI", "Code", "Materials", "Alluvium", "Build", "Profile"]


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


class Canvas:
    def __init__(self, width: int, height: int, logical_width: int, logical_height: int, title: str, filename: str):
        self.w = logical_width
        self.h = logical_height
        self.parts = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {logical_width} {logical_height}" role="img" aria-labelledby="title desc">',
            f'<title id="title">{esc(title)}</title>',
            '<desc id="desc">Meridian UI 1.0 specification mockup. Visual contract only; unavailable domain controls do not imply implementation.</desc>',
            f'<!-- Generated by scripts/generate_ui_mockups.py from docs/production/ui-mockups/mockups.json; schema meridian.ui-mockup-set/v1; generator 1.0.0; output {esc(filename)}; regenerate: python3 scripts/generate_ui_mockups.py -->',
            '<defs>',
            '<linearGradient id="viewport" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#121515"/><stop offset="1" stop-color="#090b0b"/></linearGradient>',
            '<linearGradient id="warm" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#8d8961" stop-opacity=".22"/><stop offset="1" stop-color="#c0964e" stop-opacity=".06"/></linearGradient>',
            '<filter id="shadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="8" stdDeviation="12" flood-color="#090b0b" flood-opacity=".75"/></filter>',
            '</defs>',
            f'<rect width="{logical_width}" height="{logical_height}" fill="{COLOR["background"]}"/>',
            '<g font-family="Mona Sans, system-ui, sans-serif" font-size="13" fill="#e3e1d8">',
        ]

    def rect(self, x, y, w, h, *, fill="surface", stroke="border", r=6, opacity=1, sw=1):
        self.parts.append(
            f'<rect x="{x}" y="{y}" width="{max(0, w)}" height="{max(0, h)}" rx="{r}" fill="{COLOR.get(fill, fill)}" fill-opacity="{opacity}" stroke="{COLOR.get(stroke, stroke)}" stroke-width="{sw}"/>'
        )

    def line(self, x1, y1, x2, y2, *, stroke="border", sw=1, opacity=1):
        self.parts.append(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{COLOR.get(stroke, stroke)}" stroke-width="{sw}" stroke-opacity="{opacity}"/>')

    def text(self, x, y, value, *, fill="primary", size=13, weight=450, anchor="start", mono=False, opacity=1):
        family = ' font-family="JetBrains Mono, monospace"' if mono else ""
        self.parts.append(f'<text x="{x}" y="{y}" fill="{COLOR.get(fill, fill)}" font-size="{size}" font-weight="{weight}" text-anchor="{anchor}" opacity="{opacity}"{family}>{esc(value)}</text>')

    def circle(self, x, y, radius, *, fill="muted", opacity=1):
        self.parts.append(f'<circle cx="{x}" cy="{y}" r="{radius}" fill="{COLOR.get(fill, fill)}" opacity="{opacity}"/>')

    def path(self, data, *, stroke="secondary", fill="none", sw=1.5, opacity=1):
        self.parts.append(f'<path d="{data}" fill="{COLOR.get(fill, fill)}" stroke="{COLOR.get(stroke, stroke)}" stroke-width="{sw}" stroke-linecap="round" stroke-linejoin="round" opacity="{opacity}"/>')

    def close(self):
        self.parts.extend(["</g>", "</svg>"])
        return "\n".join(self.parts) + "\n"


def header(c: Canvas, active: str, narrow: bool = False):
    c.rect(0, 0, c.w, 44, r=0)
    for index, color in enumerate(("destructive", "warning", "positive")):
        c.circle(18 + index * 18, 22, 5, fill=color, opacity=.9)
    c.text(82, 27, "Meridian", weight=650)
    c.text(144, 27, "·  Creator Alpha", fill="secondary")
    if narrow:
        utilities = [(c.w - 254, "Play"), (c.w - 194, "Build"), (c.w - 126, "Search"), (c.w - 54, "•••")]
    else:
        utilities = [(c.w - 330, "▶  Play"), (c.w - 242, "Build"), (c.w - 166, "Search"), (c.w - 82, "Settings")]
    for x, label in utilities:
        if "Play" in label:
            c.rect(x - 12, 8, 72, 28, fill="positive", stroke="positive", r=6, opacity=.22)
        c.text(x, 27, label, fill="primary" if "Play" in label else "secondary", weight=600 if "Play" in label else 450)

    c.rect(0, 44, c.w, 36, r=0)
    available = c.w - 40
    positions = []
    x = 20
    for name in WORKSPACES:
        width = max(48, 18 + len(name) * 7)
        if x + width > available:
            break
        positions.append((x, width, name))
        x += width + 4
    for x, width, name in positions:
        selected = name == active
        if selected:
            c.rect(x, 49, width, 26, fill="surface", stroke="warning", r=6, opacity=1)
            c.line(x + 8, 74, x + width - 8, 74, stroke="warning", sw=2)
        c.text(x + width / 2, 68, name, fill="primary" if selected else "secondary", size=12, weight=600 if selected else 450, anchor="middle")
    if len(positions) < len(WORKSPACES):
        c.text(c.w - 22, 68, "•••", fill="secondary", anchor="end")


def status(c: Canvas, message="Source saved", play=False):
    y = c.h - 24
    c.rect(0, y, c.w, 24, r=0)
    c.circle(14, y + 12, 3, fill="positive")
    c.text(24, y + 16, message, fill="secondary", size=11)
    if play:
        c.text(c.w / 2, y + 16, "PLAY FORK  ·  3 runtime changes  ·  Apply  ·  Discard", fill="warning", size=11, weight=650, anchor="middle")
    c.text(c.w - 18, y + 16, "Autosave  ·  60 fps", fill="muted", size=11, anchor="end", mono=True)


def panel_title(c, x, y, w, title, context="", actions="•••"):
    c.text(x + 12, y + 22, title, weight=650, size=12)
    if context:
        c.text(x + 12 + min(120, len(title) * 7 + 16), y + 22, context, fill="muted", size=11)
    c.text(x + w - 12, y + 22, actions, fill="secondary", anchor="end", size=12)
    c.line(x, y + 32, x + w, y + 32)


def rail(c, y, h):
    c.rect(8, y, 44, h, r=10)
    for i, label in enumerate(("W", "+", "⌕", "★", "◫")):
        yy = y + 18 + i * 44
        if i == 0:
            c.rect(14, yy - 11, 32, 32, fill="warning", stroke="warning", r=6, opacity=.16)
        c.text(30, yy + 10, label, fill="primary" if i == 0 else "secondary", anchor="middle", weight=650)


def browser(c, x, y, w, h, title="World"):
    c.rect(x, y, w, h, r=10)
    panel_title(c, x, y, w, title, "SOURCE")
    c.rect(x + 12, y + 44, w - 24, 30, fill="background", r=6)
    c.text(x + 24, y + 64, "Search sources", fill="muted", size=11)
    rows = [("▾", "Scene"), ("  ◇", "Camera"), ("  ◇", "Key Light"), ("  ◇", "Ground"), ("▸", "Imported"), ("▸", "Generated")]
    for i, (mark, label) in enumerate(rows):
        yy = y + 102 + i * 34
        if i == 2:
            c.rect(x + 8, yy - 19, w - 16, 28, fill="warning", stroke="warning", r=4, opacity=.12)
        c.text(x + 18, yy, f"{mark}  {label}", fill="primary" if i == 2 else "secondary", size=12)


def viewport(c, x, y, w, h, label="LIVE WORLD"):
    c.rect(x, y, w, h, fill="url(#viewport)", r=10)
    c.parts.append(f'<rect x="{x+1}" y="{y+1}" width="{max(0,w-2)}" height="{max(0,h-2)}" rx="9" fill="url(#viewport)"/>')
    c.text(x + 14, y + 24, label, fill="secondary", size=10, weight=650)
    horizon = y + h * .58
    c.path(f"M {x+20} {horizon} C {x+w*.22} {y+h*.32}, {x+w*.42} {y+h*.7}, {x+w*.58} {y+h*.46} S {x+w*.82} {y+h*.28}, {x+w-20} {horizon}", stroke="positive", sw=2, opacity=.42)
    c.path(f"M {x+20} {y+h-28} L {x+w*.38} {y+h*.56} L {x+w*.64} {y+h*.63} L {x+w-20} {y+h-28}", stroke="border", fill="surface", sw=1, opacity=.72)
    cx, cy = x + w * .58, y + h * .48
    c.rect(cx - 28, cy - 28, 56, 56, fill="warning", stroke="warning", r=4, opacity=.08, sw=2)
    c.line(cx - 42, cy, cx + 42, cy, stroke="destructive_hover", sw=2)
    c.line(cx, cy - 42, cx, cy + 42, stroke="positive", sw=2)
    c.circle(cx, cy, 4, fill="primary")


def inspector(c, x, y, w, h, title="Inspector"):
    c.rect(x, y, w, h, r=10)
    panel_title(c, x, y, w, title, "Key Light")
    c.text(x + 16, y + 58, "TRANSFORM", fill="secondary", size=10, weight=650)
    for i, (label, value) in enumerate((("Position", "4.0   6.0   2.0"), ("Rotation", "-38°  24°  0°"), ("Scale", "1.0   1.0   1.0"))):
        yy = y + 78 + i * 42
        c.text(x + 16, yy, label, fill="secondary", size=11)
        c.rect(x + w * .38, yy - 20, w * .57 - 16, 28, fill="background", r=4)
        c.text(x + w * .4, yy, value, fill="primary", size=11, mono=True)
    c.line(x + 12, y + 206, x + w - 12, y + 206)
    c.text(x + 16, y + 234, "LIGHTING / PENUMBRA", fill="secondary", size=10, weight=650)
    for i, (label, value) in enumerate((("Intensity", "1200 lm"), ("Temperature", "4200 K"), ("Shadows", "Enabled"))):
        yy = y + 266 + i * 38
        c.text(x + 16, yy, label, fill="secondary", size=11)
        c.text(x + w - 16, yy, value, fill="primary", size=11, anchor="end", mono=i < 2)
    c.rect(x + 14, y + h - 46, w - 28, 30, fill="surface", stroke="border", r=6)
    c.text(x + w / 2, y + h - 26, "Inspect Source", fill="secondary", size=11, anchor="middle", weight=600)


def shelf(c, x, y, w, h=32):
    c.rect(x, y, w, h, r=8)
    labels = [("VCS", "positive"), ("Build", "warning"), ("Diagnostics  0", "secondary"), ("Console", "secondary"), ("Profiler", "secondary"), ("Ponder Docs", "secondary")]
    xx = x + 14
    for label, color in labels:
        c.text(xx, y + 21, label, fill=color, size=11, weight=600)
        xx += 20 + len(label) * 6.4


def draw_world(c, variant):
    narrow = variant == "narrow"
    header(c, "World", narrow)
    content_y, bottom = 88, c.h - 32
    available_h = bottom - content_y - 40
    rail(c, 88, available_h)
    browser_w = 196 if narrow else min(264, c.w * .19)
    inspector_w = 260 if narrow else min(344, c.w * .24)
    if narrow:
        browser(c, 60, content_y, browser_w, available_h, "World")
        vx = 60 + browser_w + 8
        vw = c.w - vx - 8
        viewport(c, vx, content_y, vw, available_h, "LIVE WORLD · Inspector collapsed")
    else:
        browser(c, 60, content_y, browser_w, available_h, "World")
        vx = 60 + browser_w + 8
        ix = c.w - inspector_w - 8
        viewport(c, vx, content_y, ix - vx - 8, available_h)
        inspector(c, ix, content_y, inspector_w, available_h)
    shelf(c, 60, bottom - 32, c.w - 68, 32)
    status(c, "Source saved", play=True)


def draw_hub(c):
    header(c, "")
    c.text(c.w / 2, 164, "Create something worth keeping.", size=28, weight=620, anchor="middle")
    c.text(c.w / 2, 190, "Projects are local, source-authoritative, and recoverable.", fill="secondary", size=13, anchor="middle")
    card_w = min(240, (c.w - 120) / 3)
    start = (c.w - card_w * 3 - 24) / 2
    for i, (title, body, accent) in enumerate((("Create", "Start a new Meridian project", "positive"), ("Open", "Choose an existing project", "warning"), ("Recover", "Review interrupted sessions", "secondary"))):
        x = start + i * (card_w + 12)
        c.rect(x, 232, card_w, 128, r=14, stroke=accent)
        c.circle(x + 28, 264, 7, fill=accent)
        c.text(x + 20, 306, title, size=16, weight=650)
        c.text(x + 20, 332, body, fill="secondary", size=11)
    x, y, w = max(60, c.w * .17), 404, min(950, c.w * .66)
    c.text(x, y, "Recent projects", size=14, weight=650)
    for i, (name, meta, state) in enumerate((("Creator Alpha", "Today · source saved", "positive"), ("Lighting Study", "Yesterday · source saved", "positive"), ("Missing Project", "Location unavailable · Locate or Remove", "destructive"))):
        yy = y + 30 + i * 68
        c.rect(x, yy, w, 56, r=10, stroke=state if i == 2 else "border")
        c.circle(x + 22, yy + 28, 5, fill=state)
        c.text(x + 38, yy + 24, name, weight=600)
        c.text(x + 38, yy + 42, meta, fill="secondary" if i < 2 else "destructive_hover", size=11)
        c.text(x + w - 18, yy + 33, "Open" if i < 2 else "Remediate", fill="secondary", anchor="end", size=11, weight=600)
    status(c, "No project open")


def code_editor(c, x, y, w, h, contextual=False):
    c.rect(x, y, w, h, r=10)
    panel_title(c, x, y, w, "Code", "src/world.rs  ·  SOURCE")
    gutter = x + 44
    c.line(gutter, y + 32, gutter, y + h)
    lines = [
        (1, "use meridian::world::{Command, StableId};"),
        (2, ""),
        (3, "pub fn update_light(id: StableId) -> Command {"),
        (4, "    Command::set_property(id, \"intensity\", 1200.0)"),
        (5, "}"),
    ]
    for i, (number, text_value) in enumerate(lines):
        yy = y + 62 + i * 24
        c.text(gutter - 12, yy, number, fill="muted", size=11, anchor="end", mono=True)
        c.text(gutter + 14, yy, text_value, fill="primary" if i != 0 else "secondary", size=12, mono=True)
    if contextual:
        c.rect(x + 12, y + h - 72, w - 24, 54, fill="background", r=6)
        c.text(x + 24, y + h - 48, "Linked selection", fill="secondary", size=10, weight=650)
        c.text(x + 24, y + h - 28, "Key Light  ·  StableId 9f2a…", size=11, mono=True)


def draw_code(c, variant):
    header(c, "Code")
    y, h = 88, c.h - 144
    if variant == "contextual":
        viewport(c, 8, y, c.w * .43, h, "LIVE WORLD · Key Light")
        code_editor(c, c.w * .43 + 16, y, c.w * .57 - 24, h, contextual=True)
    else:
        files = 230
        browser(c, 8, y, files, h, "Project")
        code_editor(c, files + 16, y, c.w - files - 368, h)
        inspector(c, c.w - 344, y, 336, h, "Diagnostics")
    shelf(c, 8, c.h - 56, c.w - 16)
    status(c, "Code layout remembered")


def draw_modeler(c):
    header(c, "Modeler")
    y, h = 88, c.h - 144
    left, right = 228, 318
    browser(c, 8, y, left, h, "Tools · Structure")
    viewport(c, left + 16, y, c.w - left - right - 32, h, "EDITABLE MODEL · REVISION 18")
    inspector(c, c.w - right - 8, y, right, h * .62, "Properties · History")
    viewport(c, c.w - right - 8, y + h * .62 + 8, right, h * .38 - 8, "REAL-WORLD PREVIEW")
    shelf(c, 8, c.h - 56, c.w - 16)
    status(c, "Model source saved · UV and modifiers unavailable")


def draw_ui_authoring(c):
    header(c, "UI")
    y, h = 88, c.h - 144
    left, right, shelf_h = 230, 310, 180
    browser(c, 8, y, left, h, "Hierarchy · Components")
    canvas_x = left + 16
    canvas_w = c.w - left - right - 32
    viewport(c, canvas_x, y, canvas_w, h - shelf_h - 8, "RESPONSIVE CANVAS · 1440 × 900")
    c.rect(canvas_x, y + h - shelf_h, canvas_w, shelf_h, r=10)
    panel_title(c, canvas_x, y + h - shelf_h, canvas_w, "Responsive · State · Animation")
    for i, label in enumerate(("Base", "Hover", "Focused", "Disabled")):
        c.rect(canvas_x + 16 + i * 116, y + h - shelf_h + 54, 104, 30, fill="background", stroke="warning" if i == 0 else "border", r=6)
        c.text(canvas_x + 68 + i * 116, y + h - shelf_h + 74, label, fill="primary" if i == 0 else "secondary", anchor="middle", size=11)
    inspector(c, c.w - right - 8, y, right, h, "Properties · States")
    shelf(c, 8, c.h - 56, c.w - 16)
    status(c, "UI source saved")


def graph_panel(c, x, y, w, h, title):
    c.rect(x, y, w, h, r=10)
    panel_title(c, x, y, w, title)
    nodes = [(x + w * .15, y + h * .34, "Source"), (x + w * .46, y + h * .56, "Transform"), (x + w * .74, y + h * .3, "Output")]
    c.path(f"M {nodes[0][0]+80} {nodes[0][1]+24} C {x+w*.34} {nodes[0][1]}, {x+w*.34} {nodes[1][1]}, {nodes[1][0]} {nodes[1][1]+24}", stroke="warning", sw=2)
    c.path(f"M {nodes[1][0]+80} {nodes[1][1]+24} C {x+w*.62} {nodes[1][1]}, {x+w*.62} {nodes[2][1]}, {nodes[2][0]} {nodes[2][1]+24}", stroke="positive", sw=2)
    for nx, ny, label in nodes:
        c.rect(nx, ny, 96, 54, fill="background", stroke="border", r=6)
        c.text(nx + 12, ny + 22, label, weight=600, size=11)
        c.text(nx + 12, ny + 41, "SOURCE" if label == "Source" else "DERIVED", fill="muted", size=9, weight=650)


def source_panel(c, x, y, w, h, title, lines):
    c.rect(x, y, w, h, r=10)
    panel_title(c, x, y, w, title, "CANONICAL SOURCE")
    for i, line in enumerate(lines):
        c.text(x + 16, y + 58 + i * 22, line, fill="primary" if i else "secondary", size=11, mono=True)


def draw_materials_or_alluvium(c, workspace):
    header(c, workspace)
    y, h = 88, c.h - 144
    left = c.w * .58
    graph_panel(c, 8, y, left - 16, h * .58, f"{workspace} Graph")
    source_lines = ["material KeyLight {", "  roughness: 0.42", "  albedo: #8d8961", "}"] if workspace == "Materials" else ["{", '  \"schema\": \"meridian.procedural-recipe/v1\",', '  \"seed\": 42,', '  \"output\": \"placement.preview\"', "}"]
    source_panel(c, 8, y + h * .58 + 8, left - 16, h * .42 - 8, "Readable Source" if workspace == "Materials" else "Recipe Source", source_lines)
    inspector(c, left, y, c.w - left - 8, h * .48, "Parameters")
    viewport(c, left, y + h * .48 + 8, c.w - left - 8, h * .32 - 8, "VISUAL PREVIEW" if workspace == "Materials" else "GENERATED RESULT")
    c.rect(left, y + h * .80 + 8, c.w - left - 8, h * .20 - 8, r=10)
    panel_title(c, left, y + h * .80 + 8, c.w - left - 8, "Diagnostics · Provenance")
    c.text(left + 16, y + h * .80 + 62, "SOURCE  →  DERIVED  ·  license clear  ·  0 conflicts", fill="positive", size=11, mono=True)
    shelf(c, 8, c.h - 56, c.w - 16)
    status(c, f"{workspace} representations synchronized")


def table(c, x, y, w, h, title, headers, rows):
    c.rect(x, y, w, h, r=10)
    panel_title(c, x, y, w, title)
    inner_x, row_y = x + 12, y + 58
    col = (w - 24) / len(headers)
    for i, label in enumerate(headers):
        c.text(inner_x + i * col, row_y, label.upper(), fill="muted", size=9, weight=650)
    c.line(inner_x, row_y + 10, x + w - 12, row_y + 10)
    for rindex, row in enumerate(rows):
        yy = row_y + 38 + rindex * 38
        if rindex % 2:
            c.rect(inner_x - 4, yy - 20, w - 16, 30, fill="background", stroke="background", r=4)
        for i, value in enumerate(row):
            c.text(inner_x + i * col, yy, value, fill="primary" if i == 0 else "secondary", size=10, mono=i > 0)


def draw_build(c):
    header(c, "Build")
    y, h = 88, c.h - 144
    table(c, 8, y, c.w - 16, h * .48, "Build Tasks", ["Task", "State", "Duration", "Artifact"], [("Workspace check", "Complete", "12.4s", "—"), ("Creator package", "Running 72%", "18.1s", "pending"), ("Tests", "Queued", "—", "—"), ("Universal app", "Queued", "—", "Meridian.app")])
    source_panel(c, 8, y + h * .48 + 8, c.w * .68, h * .52 - 8, "Build Log", ["[12:43:08] accepted operation 018f…", "[12:43:09] compiling meridian-ui-core", "[12:43:18] artifact bound to BuildId 73ad…", "[12:43:19] durable state checkpointed"])
    c.rect(c.w * .68 + 16, y + h * .48 + 8, c.w * .32 - 24, h * .52 - 8, r=10)
    panel_title(c, c.w * .68 + 16, y + h * .48 + 8, c.w * .32 - 24, "Filters · Recovery")
    c.text(c.w * .68 + 32, y + h * .48 + 68, "Target       workspace", fill="secondary", size=11, mono=True)
    c.text(c.w * .68 + 32, y + h * .48 + 98, "Platform     macOS", fill="secondary", size=11, mono=True)
    c.text(c.w * .68 + 32, y + h * .48 + 128, "Recovery     clean", fill="positive", size=11, mono=True)
    shelf(c, 8, c.h - 56, c.w - 16)
    status(c, "Build running asynchronously")


def draw_profile(c):
    header(c, "Profile")
    y, h = 88, c.h - 144
    c.rect(8, y, c.w - 16, h * .46, r=10)
    panel_title(c, 8, y, c.w - 16, "Frame Timeline", "COMPARE · CURRENT / BASELINE")
    colors = ["positive", "warning", "secondary", "muted"]
    for row in range(5):
        yy = y + 58 + row * 46
        c.text(24, yy + 14, ("Main", "Render", "Tasks", "Streaming", "UI")[row], fill="secondary", size=10, mono=True)
        start = 110
        for i in range(8):
            width = 42 + ((row * 17 + i * 13) % 76)
            c.rect(start, yy, width, 24, fill=colors[(row + i) % len(colors)], stroke=colors[(row + i) % len(colors)], r=4, opacity=.2)
            start += width + 6
            if start > c.w - 80:
                break
    table(c, 8, y + h * .46 + 8, c.w * .54, h * .54 - 8, "Counters", ["Counter", "Current", "Baseline"], [("Frame CPU", "8.4 ms", "8.9 ms"), ("Frame GPU", "10.2 ms", "10.1 ms"), ("UI layout", "0.7 ms", "0.8 ms"), ("Resident", "1.21 GiB", "1.18 GiB")])
    graph_panel(c, c.w * .54 + 16, y + h * .46 + 8, c.w * .46 - 24, h * .54 - 8, "Flame Graph · Drill-down")
    shelf(c, 8, c.h - 56, c.w - 16)
    status(c, "Capture loaded · unsupported counters remain explicit")


def draw_settings(c):
    header(c, "")
    y, h = 96, c.h - 136
    nav = 260
    c.rect(120, y, nav, h, r=10)
    panel_title(c, 120, y, nav, "Settings")
    c.rect(134, y + 46, nav - 28, 30, fill="background", r=6)
    c.text(148, y + 66, "Search settings", fill="muted", size=11)
    for i, label in enumerate(("Appearance", "Accessibility", "Input", "Workspaces", "Build", "Advanced")):
        yy = y + 112 + i * 42
        if i == 0:
            c.rect(130, yy - 22, nav - 20, 30, fill="warning", stroke="warning", r=6, opacity=.12)
        c.text(148, yy, label, fill="primary" if i == 0 else "secondary", size=12, weight=600 if i == 0 else 450)
    x, w = 388, c.w - 508
    c.rect(x, y, w, h, r=10)
    panel_title(c, x, y, w, "Appearance", "Product preferences")
    c.text(x + 24, y + 76, "Theme", weight=600)
    c.text(x + w - 24, y + 76, "Meridian Dark", fill="secondary", anchor="end")
    c.line(x + 20, y + 96, x + w - 20, y + 96)
    for i, (label, value) in enumerate((("Density", "Standard"), ("Text scale", "100%"), ("Contrast", "Standard"), ("Motion", "Full"), ("Adaptive layout", "On · pins always win"))):
        yy = y + 136 + i * 54
        c.text(x + 24, yy, label, fill="secondary")
        c.rect(x + w - 220, yy - 22, 196, 32, fill="background", r=6)
        c.text(x + w - 36, yy, value, anchor="end", size=11)
    c.rect(x + 24, y + h - 58, 168, 32, fill="surface", stroke="destructive", r=6)
    c.text(x + 108, y + h - 37, "Reset workspace state", fill="destructive_hover", size=11, weight=600, anchor="middle")
    status(c, "Settings are local user state")


def draw_recovery(c):
    header(c, "")
    w, h = min(760, c.w - 80), min(560, c.h - 150)
    x, y = (c.w - w) / 2, 116
    c.parts.append('<g filter="url(#shadow)">')
    c.rect(x, y, w, h, r=14, stroke="warning")
    c.parts.append('</g>')
    c.text(x + 28, y + 48, "Recovery", size=22, weight=650)
    c.text(x + 28, y + 76, "Meridian found a valid source document and a newer interrupted checkpoint.", fill="secondary", size=12)
    c.rect(x + 24, y + 108, w - 48, 104, fill="background", r=10)
    c.text(x + 42, y + 138, "AUTHORITATIVE SOURCE", fill="positive", size=10, weight=650)
    c.text(x + 42, y + 166, "creator-project.json  ·  saved 12:41:06  ·  hash 72bf…", size=11, mono=True)
    c.text(x + 42, y + 190, "Safe to open unchanged", fill="secondary", size=11)
    c.rect(x + 24, y + 226, w - 48, 104, fill="background", stroke="warning", r=10)
    c.text(x + 42, y + 256, "RECOVERY CHECKPOINT", fill="warning", size=10, weight=650)
    c.text(x + 42, y + 284, "3 accepted commands  ·  source write not confirmed", size=11, mono=True)
    c.text(x + 42, y + 308, "Inspect the semantic diff before applying", fill="secondary", size=11)
    buttons = (("Open source", "positive"), ("Review checkpoint", "warning"), ("Discard checkpoint", "destructive"))
    bx = x + 24
    for label, color in buttons:
        bw = 150 + len(label) * 2
        c.rect(bx, y + h - 66, bw, 36, fill=color, stroke=color, r=6, opacity=.14)
        c.text(bx + bw / 2, y + h - 42, label, fill="primary" if color != "destructive" else "destructive_hover", size=11, weight=650, anchor="middle")
        bx += bw + 12
    status(c, "Recovery requires an explicit choice")


def generate(entry, version):
    width, height = entry["width"], entry["height"]
    logical_width = entry.get("logical_width", width)
    logical_height = entry.get("logical_height", height)
    c = Canvas(width, height, logical_width, logical_height, entry["title"], entry["file"])
    workspace, variant = entry["workspace"], entry["variant"]
    if workspace == "Hub":
        draw_hub(c)
    elif workspace == "World":
        draw_world(c, variant)
    elif workspace == "Code":
        draw_code(c, variant)
    elif workspace == "Modeler":
        draw_modeler(c)
    elif workspace == "UI":
        draw_ui_authoring(c)
    elif workspace in ("Materials", "Alluvium"):
        draw_materials_or_alluvium(c, workspace)
    elif workspace == "Build":
        draw_build(c)
    elif workspace == "Profile":
        draw_profile(c)
    elif workspace == "Settings":
        draw_settings(c)
    elif workspace == "Recovery":
        draw_recovery(c)
    else:
        raise ValueError(f"unknown workspace {workspace}")
    if variant == "high-contrast":
        c.parts.insert(-1, f'<rect x="2" y="2" width="{c.w-4}" height="{c.h-4}" rx="10" fill="none" stroke="{COLOR["primary"]}" stroke-width="2" pointer-events="none"/>')
    return c.close()


def main():
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if manifest.get("schema") != "meridian.ui-mockup-set/v1":
        raise SystemExit("unsupported mockup manifest schema")
    OUT.mkdir(parents=True, exist_ok=True)
    expected = {entry["file"] for entry in manifest["outputs"]}
    for stale in OUT.glob("*.svg"):
        if stale.name not in expected:
            stale.unlink()
    for entry in manifest["outputs"]:
        target = OUT / entry["file"]
        target.write_text(generate(entry, manifest["generator_version"]), encoding="utf-8")
    print(f"generated {len(expected)} Meridian UI mockups in {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
