// @generated by scripts/generate_ui_icons.py
// Input schema: meridian.ui-icons/v1; generator version: 1
// Regenerate: python3 scripts/generate_ui_icons.py --write

// play.svg SHA-256 d7c34786135922a92b6896f6c2384ceeb0346afbf6041dc79982011411409833
static ICON_PLAY_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 5.0, y: 5.0 }),
    UiPathCommand::LineTo(UiPoint { x: 5.120973, y: 4.314383 }),
    UiPathCommand::LineTo(UiPoint { x: 5.46964, y: 3.711774 }),
    UiPathCommand::LineTo(UiPoint { x: 6.003751, y: 3.265196 }),
    UiPathCommand::LineTo(UiPoint { x: 6.658584, y: 3.028764 }),
    UiPathCommand::LineTo(UiPoint { x: 7.354788, y: 3.031127 }),
    UiPathCommand::LineTo(UiPoint { x: 8.008, y: 3.272 }),
    UiPathCommand::LineTo(UiPoint { x: 20.005, y: 10.27 }),
    UiPathCommand::LineTo(UiPoint { x: 20.534816, y: 10.716076 }),
    UiPathCommand::LineTo(UiPoint { x: 20.880721, y: 11.316107 }),
    UiPathCommand::LineTo(UiPoint { x: 21.001235, y: 11.998137 }),
    UiPathCommand::LineTo(UiPoint { x: 20.881905, y: 12.680375 }),
    UiPathCommand::LineTo(UiPoint { x: 20.537041, y: 13.281006 }),
    UiPathCommand::LineTo(UiPoint { x: 20.008, y: 13.728 }),
    UiPathCommand::LineTo(UiPoint { x: 8.008, y: 20.728 }),
    UiPathCommand::LineTo(UiPoint { x: 7.354788, y: 20.968873 }),
    UiPathCommand::LineTo(UiPoint { x: 6.658584, y: 20.971236 }),
    UiPathCommand::LineTo(UiPoint { x: 6.003751, y: 20.734804 }),
    UiPathCommand::LineTo(UiPoint { x: 5.46964, y: 20.288226 }),
    UiPathCommand::LineTo(UiPoint { x: 5.120973, y: 19.685617 }),
    UiPathCommand::LineTo(UiPoint { x: 5.0, y: 19.0 }),
    UiPathCommand::Close,
];
static ICON_PLAY: &[&[UiPathCommand]] = &[
    ICON_PLAY_0,
];

// square.svg SHA-256 bd979354f0ab184b95cecf03eedefe40c2dc65830ac6d7e60017b2b25a354acb
static ICON_STOP_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 5.0, y: 3.0 }),
    UiPathCommand::LineTo(UiPoint { x: 19.0, y: 3.0 }),
    UiPathCommand::QuadraticTo { control: UiPoint { x: 21.0, y: 3.0 }, end: UiPoint { x: 21.0, y: 5.0 } },
    UiPathCommand::LineTo(UiPoint { x: 21.0, y: 19.0 }),
    UiPathCommand::QuadraticTo { control: UiPoint { x: 21.0, y: 21.0 }, end: UiPoint { x: 19.0, y: 21.0 } },
    UiPathCommand::LineTo(UiPoint { x: 5.0, y: 21.0 }),
    UiPathCommand::QuadraticTo { control: UiPoint { x: 3.0, y: 21.0 }, end: UiPoint { x: 3.0, y: 19.0 } },
    UiPathCommand::LineTo(UiPoint { x: 3.0, y: 5.0 }),
    UiPathCommand::QuadraticTo { control: UiPoint { x: 3.0, y: 3.0 }, end: UiPoint { x: 5.0, y: 3.0 } },
    UiPathCommand::Close,
];
static ICON_STOP: &[&[UiPathCommand]] = &[
    ICON_STOP_0,
];

// hammer.svg SHA-256 db75caf31bd080726be0c2dab09372498b999cbdcf10c756f44636831f9529f5
static ICON_BUILD_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 15.0, y: 12.0 }),
    UiPathCommand::LineTo(UiPoint { x: 5.627, y: 21.373 }),
    UiPathCommand::LineTo(UiPoint { x: 4.938756, y: 21.833036 }),
    UiPathCommand::LineTo(UiPoint { x: 4.126854, y: 21.994674 }),
    UiPathCommand::LineTo(UiPoint { x: 3.314897, y: 21.833306 }),
    UiPathCommand::LineTo(UiPoint { x: 2.6265, y: 21.3735 }),
    UiPathCommand::LineTo(UiPoint { x: 2.166464, y: 20.685256 }),
    UiPathCommand::LineTo(UiPoint { x: 2.004826, y: 19.873354 }),
    UiPathCommand::LineTo(UiPoint { x: 2.166194, y: 19.061397 }),
    UiPathCommand::LineTo(UiPoint { x: 2.626, y: 18.373 }),
    UiPathCommand::LineTo(UiPoint { x: 12.0, y: 9.0 }),
];
static ICON_BUILD_1: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 18.0, y: 15.0 }),
    UiPathCommand::LineTo(UiPoint { x: 22.0, y: 11.0 }),
];
static ICON_BUILD_2: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 21.5, y: 11.5 }),
    UiPathCommand::LineTo(UiPoint { x: 19.586, y: 9.586 }),
    UiPathCommand::LineTo(UiPoint { x: 19.15238, y: 8.937277 }),
    UiPathCommand::LineTo(UiPoint { x: 19.0, y: 8.172 }),
    UiPathCommand::LineTo(UiPoint { x: 19.0, y: 7.828 }),
    UiPathCommand::LineTo(UiPoint { x: 18.84762, y: 7.062723 }),
    UiPathCommand::LineTo(UiPoint { x: 18.414, y: 6.414 }),
    UiPathCommand::LineTo(UiPoint { x: 16.757, y: 4.757 }),
    UiPathCommand::LineTo(UiPoint { x: 14.811176, y: 3.456871 }),
    UiPathCommand::LineTo(UiPoint { x: 12.516, y: 3.0 }),
    UiPathCommand::LineTo(UiPoint { x: 9.0, y: 3.0 }),
    UiPathCommand::LineTo(UiPoint { x: 10.243, y: 4.243 }),
    UiPathCommand::LineTo(UiPoint { x: 11.543321, y: 6.189286 }),
    UiPathCommand::LineTo(UiPoint { x: 12.0, y: 8.485 }),
    UiPathCommand::LineTo(UiPoint { x: 12.0, y: 10.0 }),
    UiPathCommand::LineTo(UiPoint { x: 14.0, y: 12.0 }),
    UiPathCommand::LineTo(UiPoint { x: 15.172, y: 12.0 }),
    UiPathCommand::LineTo(UiPoint { x: 15.937277, y: 12.15238 }),
    UiPathCommand::LineTo(UiPoint { x: 16.586, y: 12.586 }),
    UiPathCommand::LineTo(UiPoint { x: 18.5, y: 14.5 }),
];
static ICON_BUILD: &[&[UiPathCommand]] = &[
    ICON_BUILD_0,
    ICON_BUILD_1,
    ICON_BUILD_2,
];

// search.svg SHA-256 283d371c2e433817bb9c0c8310caa6c77fa4177c0f4f1168d9c83b97af7389dc
static ICON_SEARCH_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 21.0, y: 21.0 }),
    UiPathCommand::LineTo(UiPoint { x: 16.66, y: 16.66 }),
];
static ICON_SEARCH_1: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 19.0, y: 11.0 }),
    UiPathCommand::CubicTo { control_a: UiPoint { x: 19.0, y: 15.418278 }, control_b: UiPoint { x: 15.418278, y: 19.0 }, end: UiPoint { x: 11.0, y: 19.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 6.581722, y: 19.0 }, control_b: UiPoint { x: 3.0, y: 15.418278 }, end: UiPoint { x: 3.0, y: 11.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 3.0, y: 6.581722 }, control_b: UiPoint { x: 6.581722, y: 3.0 }, end: UiPoint { x: 11.0, y: 3.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 15.418278, y: 3.0 }, control_b: UiPoint { x: 19.0, y: 6.581722 }, end: UiPoint { x: 19.0, y: 11.0 } },
    UiPathCommand::Close,
];
static ICON_SEARCH: &[&[UiPathCommand]] = &[
    ICON_SEARCH_0,
    ICON_SEARCH_1,
];

// settings.svg SHA-256 0ae27fd0f81999229e3127ac96c5b32edfea448e291d509e76212b917551d66b
static ICON_SETTINGS_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 9.671, y: 4.136 }),
    UiPathCommand::LineTo(UiPoint { x: 9.907674, y: 3.310679 }),
    UiPathCommand::LineTo(UiPoint { x: 10.426101, y: 2.62628 }),
    UiPathCommand::LineTo(UiPoint { x: 11.156487, y: 2.174941 }),
    UiPathCommand::LineTo(UiPoint { x: 12.0005, y: 2.017427 }),
    UiPathCommand::LineTo(UiPoint { x: 12.844513, y: 2.174941 }),
    UiPathCommand::LineTo(UiPoint { x: 13.574899, y: 2.62628 }),
    UiPathCommand::LineTo(UiPoint { x: 14.093326, y: 3.310679 }),
    UiPathCommand::LineTo(UiPoint { x: 14.33, y: 4.136 }),
    UiPathCommand::LineTo(UiPoint { x: 14.576667, y: 4.993604 }),
    UiPathCommand::LineTo(UiPoint { x: 15.126449, y: 5.696504 }),
    UiPathCommand::LineTo(UiPoint { x: 15.89939, y: 6.142476 }),
    UiPathCommand::LineTo(UiPoint { x: 16.783079, y: 6.266662 }),
    UiPathCommand::LineTo(UiPoint { x: 17.649, y: 6.051 }),
    UiPathCommand::LineTo(UiPoint { x: 18.480919, y: 5.84561 }),
    UiPathCommand::LineTo(UiPoint { x: 19.331, y: 5.953486 }),
    UiPathCommand::LineTo(UiPoint { x: 20.085247, y: 6.360162 }),
    UiPathCommand::LineTo(UiPoint { x: 20.642517, y: 7.011104 }),
    UiPathCommand::LineTo(UiPoint { x: 20.928079, y: 7.819021 }),
    UiPathCommand::LineTo(UiPoint { x: 20.90364, y: 8.67557 }),
    UiPathCommand::LineTo(UiPoint { x: 20.572478, y: 9.465891 }),
    UiPathCommand::LineTo(UiPoint { x: 19.979, y: 10.084 }),
    UiPathCommand::LineTo(UiPoint { x: 19.359808, y: 10.726198 }),
    UiPathCommand::LineTo(UiPoint { x: 19.025951, y: 11.553457 }),
    UiPathCommand::LineTo(UiPoint { x: 19.025951, y: 12.445543 }),
    UiPathCommand::LineTo(UiPoint { x: 19.359808, y: 13.272802 }),
    UiPathCommand::LineTo(UiPoint { x: 19.979, y: 13.915 }),
    UiPathCommand::LineTo(UiPoint { x: 20.572478, y: 14.533109 }),
    UiPathCommand::LineTo(UiPoint { x: 20.90364, y: 15.32343 }),
    UiPathCommand::LineTo(UiPoint { x: 20.928079, y: 16.179979 }),
    UiPathCommand::LineTo(UiPoint { x: 20.642517, y: 16.987896 }),
    UiPathCommand::LineTo(UiPoint { x: 20.085247, y: 17.638838 }),
    UiPathCommand::LineTo(UiPoint { x: 19.331, y: 18.045514 }),
    UiPathCommand::LineTo(UiPoint { x: 18.480919, y: 18.15339 }),
    UiPathCommand::LineTo(UiPoint { x: 17.649, y: 17.948 }),
    UiPathCommand::LineTo(UiPoint { x: 16.783079, y: 17.732338 }),
    UiPathCommand::LineTo(UiPoint { x: 15.89939, y: 17.856524 }),
    UiPathCommand::LineTo(UiPoint { x: 15.126449, y: 18.302496 }),
    UiPathCommand::LineTo(UiPoint { x: 14.576667, y: 19.005396 }),
    UiPathCommand::LineTo(UiPoint { x: 14.33, y: 19.863 }),
    UiPathCommand::LineTo(UiPoint { x: 14.093326, y: 20.688321 }),
    UiPathCommand::LineTo(UiPoint { x: 13.574899, y: 21.37272 }),
    UiPathCommand::LineTo(UiPoint { x: 12.844513, y: 21.824059 }),
    UiPathCommand::LineTo(UiPoint { x: 12.0005, y: 21.981573 }),
    UiPathCommand::LineTo(UiPoint { x: 11.156487, y: 21.824059 }),
    UiPathCommand::LineTo(UiPoint { x: 10.426101, y: 21.37272 }),
    UiPathCommand::LineTo(UiPoint { x: 9.907674, y: 20.688321 }),
    UiPathCommand::LineTo(UiPoint { x: 9.671, y: 19.863 }),
    UiPathCommand::LineTo(UiPoint { x: 9.424361, y: 19.00508 }),
    UiPathCommand::LineTo(UiPoint { x: 8.874395, y: 18.301947 }),
    UiPathCommand::LineTo(UiPoint { x: 8.101139, y: 17.855928 }),
    UiPathCommand::LineTo(UiPoint { x: 7.217124, y: 17.73193 }),
    UiPathCommand::LineTo(UiPoint { x: 6.351, y: 17.948 }),
    UiPathCommand::LineTo(UiPoint { x: 5.519081, y: 18.15339 }),
    UiPathCommand::LineTo(UiPoint { x: 4.669, y: 18.045514 }),
    UiPathCommand::LineTo(UiPoint { x: 3.914753, y: 17.638838 }),
    UiPathCommand::LineTo(UiPoint { x: 3.357483, y: 16.987896 }),
    UiPathCommand::LineTo(UiPoint { x: 3.071921, y: 16.179979 }),
    UiPathCommand::LineTo(UiPoint { x: 3.09636, y: 15.32343 }),
    UiPathCommand::LineTo(UiPoint { x: 3.427522, y: 14.533109 }),
    UiPathCommand::LineTo(UiPoint { x: 4.021, y: 13.915 }),
    UiPathCommand::LineTo(UiPoint { x: 4.640192, y: 13.272802 }),
    UiPathCommand::LineTo(UiPoint { x: 4.974049, y: 12.445543 }),
    UiPathCommand::LineTo(UiPoint { x: 4.974049, y: 11.553457 }),
    UiPathCommand::LineTo(UiPoint { x: 4.640192, y: 10.726198 }),
    UiPathCommand::LineTo(UiPoint { x: 4.021, y: 10.084 }),
    UiPathCommand::LineTo(UiPoint { x: 3.428431, y: 9.465888 }),
    UiPathCommand::LineTo(UiPoint { x: 3.097901, y: 8.675982 }),
    UiPathCommand::LineTo(UiPoint { x: 3.073671, y: 7.820053 }),
    UiPathCommand::LineTo(UiPoint { x: 3.358984, y: 7.012713 }),
    UiPathCommand::LineTo(UiPoint { x: 3.915637, y: 6.362068 }),
    UiPathCommand::LineTo(UiPoint { x: 4.669091, y: 5.955241 }),
    UiPathCommand::LineTo(UiPoint { x: 5.518456, y: 5.846707 }),
    UiPathCommand::LineTo(UiPoint { x: 6.35, y: 6.051 }),
    UiPathCommand::LineTo(UiPoint { x: 7.215921, y: 6.266662 }),
    UiPathCommand::LineTo(UiPoint { x: 8.09961, y: 6.142476 }),
    UiPathCommand::LineTo(UiPoint { x: 8.872551, y: 5.696504 }),
    UiPathCommand::LineTo(UiPoint { x: 9.422333, y: 4.993604 }),
    UiPathCommand::LineTo(UiPoint { x: 9.669, y: 4.136 }),
];
static ICON_SETTINGS_1: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 15.0, y: 12.0 }),
    UiPathCommand::CubicTo { control_a: UiPoint { x: 15.0, y: 13.656854 }, control_b: UiPoint { x: 13.656854, y: 15.0 }, end: UiPoint { x: 12.0, y: 15.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 10.343146, y: 15.0 }, control_b: UiPoint { x: 9.0, y: 13.656854 }, end: UiPoint { x: 9.0, y: 12.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 9.0, y: 10.343146 }, control_b: UiPoint { x: 10.343146, y: 9.0 }, end: UiPoint { x: 12.0, y: 9.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 13.656854, y: 9.0 }, control_b: UiPoint { x: 15.0, y: 10.343146 }, end: UiPoint { x: 15.0, y: 12.0 } },
    UiPathCommand::Close,
];
static ICON_SETTINGS: &[&[UiPathCommand]] = &[
    ICON_SETTINGS_0,
    ICON_SETTINGS_1,
];

// ellipsis.svg SHA-256 4f495cc72013ffdfec677f03b33a150f7b4dd741979283fd6853a09024bca112
static ICON_MORE_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 13.0, y: 12.0 }),
    UiPathCommand::CubicTo { control_a: UiPoint { x: 13.0, y: 12.552285 }, control_b: UiPoint { x: 12.552285, y: 13.0 }, end: UiPoint { x: 12.0, y: 13.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 11.447715, y: 13.0 }, control_b: UiPoint { x: 11.0, y: 12.552285 }, end: UiPoint { x: 11.0, y: 12.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 11.0, y: 11.447715 }, control_b: UiPoint { x: 11.447715, y: 11.0 }, end: UiPoint { x: 12.0, y: 11.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 12.552285, y: 11.0 }, control_b: UiPoint { x: 13.0, y: 11.447715 }, end: UiPoint { x: 13.0, y: 12.0 } },
    UiPathCommand::Close,
];
static ICON_MORE_1: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 20.0, y: 12.0 }),
    UiPathCommand::CubicTo { control_a: UiPoint { x: 20.0, y: 12.552285 }, control_b: UiPoint { x: 19.552285, y: 13.0 }, end: UiPoint { x: 19.0, y: 13.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 18.447715, y: 13.0 }, control_b: UiPoint { x: 18.0, y: 12.552285 }, end: UiPoint { x: 18.0, y: 12.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 18.0, y: 11.447715 }, control_b: UiPoint { x: 18.447715, y: 11.0 }, end: UiPoint { x: 19.0, y: 11.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 19.552285, y: 11.0 }, control_b: UiPoint { x: 20.0, y: 11.447715 }, end: UiPoint { x: 20.0, y: 12.0 } },
    UiPathCommand::Close,
];
static ICON_MORE_2: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 6.0, y: 12.0 }),
    UiPathCommand::CubicTo { control_a: UiPoint { x: 6.0, y: 12.552285 }, control_b: UiPoint { x: 5.552285, y: 13.0 }, end: UiPoint { x: 5.0, y: 13.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 4.447715, y: 13.0 }, control_b: UiPoint { x: 4.0, y: 12.552285 }, end: UiPoint { x: 4.0, y: 12.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 4.0, y: 11.447715 }, control_b: UiPoint { x: 4.447715, y: 11.0 }, end: UiPoint { x: 5.0, y: 11.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 5.552285, y: 11.0 }, control_b: UiPoint { x: 6.0, y: 11.447715 }, end: UiPoint { x: 6.0, y: 12.0 } },
    UiPathCommand::Close,
];
static ICON_MORE: &[&[UiPathCommand]] = &[
    ICON_MORE_0,
    ICON_MORE_1,
    ICON_MORE_2,
];

// x.svg SHA-256 4a9cdab38fbb96162e7dace28e33f4ca0e49d8963a6162abc3d4691b7d675117
static ICON_CLOSE_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 18.0, y: 6.0 }),
    UiPathCommand::LineTo(UiPoint { x: 6.0, y: 18.0 }),
];
static ICON_CLOSE_1: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 6.0, y: 6.0 }),
    UiPathCommand::LineTo(UiPoint { x: 18.0, y: 18.0 }),
];
static ICON_CLOSE: &[&[UiPathCommand]] = &[
    ICON_CLOSE_0,
    ICON_CLOSE_1,
];

// chevron-down.svg SHA-256 66ea878e72ed3488bb3b464c39dfdccee8d1f78e560dccea40e5e12da0e87e87
static ICON_CHEVRONDOWN_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 6.0, y: 9.0 }),
    UiPathCommand::LineTo(UiPoint { x: 12.0, y: 15.0 }),
    UiPathCommand::LineTo(UiPoint { x: 18.0, y: 9.0 }),
];
static ICON_CHEVRONDOWN: &[&[UiPathCommand]] = &[
    ICON_CHEVRONDOWN_0,
];

// chevron-right.svg SHA-256 2758143d7b2434e4aa7307dfd34405c87909ff4052f21b5f3f40d45224b4f19b
static ICON_CHEVRONRIGHT_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 9.0, y: 18.0 }),
    UiPathCommand::LineTo(UiPoint { x: 15.0, y: 12.0 }),
    UiPathCommand::LineTo(UiPoint { x: 9.0, y: 6.0 }),
];
static ICON_CHEVRONRIGHT: &[&[UiPathCommand]] = &[
    ICON_CHEVRONRIGHT_0,
];

// triangle-alert.svg SHA-256 4866f38b8560d410f21e3226413e0b77997b6dfbb6931fadfe0a0d5aef9ffeb4
static ICON_WARNING_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 21.73, y: 18.0 }),
    UiPathCommand::LineTo(UiPoint { x: 13.73, y: 4.0 }),
    UiPathCommand::LineTo(UiPoint { x: 13.283733, y: 3.460897 }),
    UiPathCommand::LineTo(UiPoint { x: 12.679053, y: 3.10855 }),
    UiPathCommand::LineTo(UiPoint { x: 11.99, y: 2.986103 }),
    UiPathCommand::LineTo(UiPoint { x: 11.300947, y: 3.10855 }),
    UiPathCommand::LineTo(UiPoint { x: 10.696267, y: 3.460897 }),
    UiPathCommand::LineTo(UiPoint { x: 10.25, y: 4.0 }),
    UiPathCommand::LineTo(UiPoint { x: 2.25, y: 18.0 }),
    UiPathCommand::LineTo(UiPoint { x: 2.011883, y: 18.655662 }),
    UiPathCommand::LineTo(UiPoint { x: 2.013428, y: 19.353222 }),
    UiPathCommand::LineTo(UiPoint { x: 2.254446, y: 20.007823 }),
    UiPathCommand::LineTo(UiPoint { x: 2.705619, y: 20.539834 }),
    UiPathCommand::LineTo(UiPoint { x: 3.312061, y: 20.884537 }),
    UiPathCommand::LineTo(UiPoint { x: 4.0, y: 21.0 }),
    UiPathCommand::LineTo(UiPoint { x: 20.0, y: 21.0 }),
    UiPathCommand::LineTo(UiPoint { x: 20.683595, y: 20.878801 }),
    UiPathCommand::LineTo(UiPoint { x: 21.284572, y: 20.531211 }),
    UiPathCommand::LineTo(UiPoint { x: 21.730513, y: 19.999113 }),
    UiPathCommand::LineTo(UiPoint { x: 21.967684, y: 19.346624 }),
    UiPathCommand::LineTo(UiPoint { x: 21.967506, y: 18.652367 }),
    UiPathCommand::LineTo(UiPoint { x: 21.73, y: 18.0 }),
];
static ICON_WARNING_1: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 12.0, y: 9.0 }),
    UiPathCommand::LineTo(UiPoint { x: 12.0, y: 13.0 }),
];
static ICON_WARNING_2: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 12.0, y: 17.0 }),
    UiPathCommand::LineTo(UiPoint { x: 12.01, y: 17.0 }),
];
static ICON_WARNING: &[&[UiPathCommand]] = &[
    ICON_WARNING_0,
    ICON_WARNING_1,
    ICON_WARNING_2,
];

// circle-x.svg SHA-256 bcd8788901e6f29e1b231a81ba5e707d083d06cb4848a28f29407fab4f8e0b64
static ICON_ERROR_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 22.0, y: 12.0 }),
    UiPathCommand::CubicTo { control_a: UiPoint { x: 22.0, y: 17.522847 }, control_b: UiPoint { x: 17.522847, y: 22.0 }, end: UiPoint { x: 12.0, y: 22.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 6.477153, y: 22.0 }, control_b: UiPoint { x: 2.0, y: 17.522847 }, end: UiPoint { x: 2.0, y: 12.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 2.0, y: 6.477153 }, control_b: UiPoint { x: 6.477153, y: 2.0 }, end: UiPoint { x: 12.0, y: 2.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 17.522847, y: 2.0 }, control_b: UiPoint { x: 22.0, y: 6.477153 }, end: UiPoint { x: 22.0, y: 12.0 } },
    UiPathCommand::Close,
];
static ICON_ERROR_1: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 15.0, y: 9.0 }),
    UiPathCommand::LineTo(UiPoint { x: 9.0, y: 15.0 }),
];
static ICON_ERROR_2: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 9.0, y: 9.0 }),
    UiPathCommand::LineTo(UiPoint { x: 15.0, y: 15.0 }),
];
static ICON_ERROR: &[&[UiPathCommand]] = &[
    ICON_ERROR_0,
    ICON_ERROR_1,
    ICON_ERROR_2,
];

// circle-check.svg SHA-256 3e519680ab8e2a8ad8f56a340c10d61957d872237aaa868cf324b0900a74f384
static ICON_SUCCESS_0: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 22.0, y: 12.0 }),
    UiPathCommand::CubicTo { control_a: UiPoint { x: 22.0, y: 17.522847 }, control_b: UiPoint { x: 17.522847, y: 22.0 }, end: UiPoint { x: 12.0, y: 22.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 6.477153, y: 22.0 }, control_b: UiPoint { x: 2.0, y: 17.522847 }, end: UiPoint { x: 2.0, y: 12.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 2.0, y: 6.477153 }, control_b: UiPoint { x: 6.477153, y: 2.0 }, end: UiPoint { x: 12.0, y: 2.0 } },
    UiPathCommand::CubicTo { control_a: UiPoint { x: 17.522847, y: 2.0 }, control_b: UiPoint { x: 22.0, y: 6.477153 }, end: UiPoint { x: 22.0, y: 12.0 } },
    UiPathCommand::Close,
];
static ICON_SUCCESS_1: &[UiPathCommand] = &[
    UiPathCommand::MoveTo(UiPoint { x: 9.0, y: 12.0 }),
    UiPathCommand::LineTo(UiPoint { x: 11.0, y: 14.0 }),
    UiPathCommand::LineTo(UiPoint { x: 15.0, y: 10.0 }),
];
static ICON_SUCCESS: &[&[UiPathCommand]] = &[
    ICON_SUCCESS_0,
    ICON_SUCCESS_1,
];

pub(crate) const fn source_icon_paths(icon: IconId) -> &'static [&'static [UiPathCommand]] {
    match icon {
        IconId::Play => ICON_PLAY,
        IconId::Stop => ICON_STOP,
        IconId::Build => ICON_BUILD,
        IconId::Search => ICON_SEARCH,
        IconId::Settings => ICON_SETTINGS,
        IconId::More => ICON_MORE,
        IconId::Close => ICON_CLOSE,
        IconId::ChevronDown => ICON_CHEVRONDOWN,
        IconId::ChevronRight => ICON_CHEVRONRIGHT,
        IconId::Warning => ICON_WARNING,
        IconId::Error => ICON_ERROR,
        IconId::Success => ICON_SUCCESS,
    }
}
